/**
 * What's on www.knowall.ai, so Sallie can point visitors to the right place.
 * Curated by hand from the site's pages; keep it in step when sections move.
 */
export const siteIndex = `Website guide (https://www.knowall.ai). Link to these when relevant, using markdown links:

Home page sections:
- Our Services (/#services): AI Consultancy — expert guidance on implementing AI solutions tailored to the business; Microsoft Copilot Development — custom Copilots that enhance productivity and automate workflows; Value-for-Value Transactions — peer-to-peer Bitcoin transfers between autonomous AI agents.
- Building AI Agents & Microsoft Copilots (/#copilots): custom Copilot development and orchestrated multi-agent teams (AutoGen).
- Zaplie (/#zaplie, code at https://github.com/knowall-ai/zaplie-webapp): open-source platform that integrates Microsoft Teams with Bitcoin Lightning microtransactions and AI agents on a value-for-value model — instant Lightning payments reward teammates, clients and AI agents in proportion to the value they deliver.
- Zapdesk (/#zapdesk, https://zapdesk.knowall.ai): Azure DevOps-powered support ticketing.
- Thyme (/#thyme, https://getthyme.ai): time tracking for Microsoft Dynamics 365 Business Central — a timesheet web app that keeps Business Central Jobs and Job Journal Lines in sync automatically.
- T-Minus-15 (/#tminus15, https://github.com/T-Minus-15): our open-source delivery methodology and book, "Secrets of an Elite DevOps Team" — Agile and DevOps distilled into fifteen steps, delivering features in fifteen days or less; it also configures our AI agents.
- Sallie for Sales (/#sallie): that's me — an AI sales copilot living in Microsoft Teams that drafts proposals and quotations, tracks the pipeline and chases deals, always checking with a human before anything reaches a client. Visitors can book a demo from that section.
- Meet the Agents (/#agents): the AI agents that work alongside the team across the T-Minus-15 lifecycle — Sallie (Salesperson), Poppie (Planner), Preppie (Prepper), Archie (Architect), Dannie (Designer), Ernie (Engineer), Teddie (Tester), Pennie (Penetration Tester), Ollie (Operator), Allie (Accountant) and Zaplie (Rewards Agent).
- Meet the Team (/#team): Ben Weeks (Chief Builder), Valeriia Khudiakova (Chief Planner), Akash Jadhav (Senior Engineer), Edit Weeks (Chief Tester).
- Get In Touch (/#contact): email, WhatsApp and Nostr.

Other pages:
- Our Story (/story): the company's story and updates, straight from our Nostr feed.
- Shop (/shop): our products and merchandise, listed on Nostr and paid for with Bitcoin over Lightning. Policies: shipping (/shop/policies/shipping), refunds (/shop/policies/refunds), privacy (/shop/policies/privacy), terms (/shop/policies/terms).

Presentations (https://www.knowall.ai/presentations/) — our slide decks, each opening in the browser. Use them: when a visitor wants more detail or depth on a topic, give a short answer and then link the deck that covers it "for more information". Never paste a whole deck into chat.
- Agentic AI Solutions (https://www.knowall.ai/presentations/agentic-ai-solutions.html): our flagship pitch, "Agentic AI that works while you sleep". Why agents beat a "better search box" Copilot; Preppie the AI requirements analyst; the eight core T-Minus-15 delivery agents the deck features (Sallie, Poppie, Preppie, Dannie, Ernie, Teddie, Ollie, Archie) running in Claude Code, Azure AI Foundry and OpenClaw — the website's Meet the Agents section shows the full team of eleven, adding Pennie, Allie and Zaplie; the agents we run ourselves (Sallie, Allie for Accounts, Nodie the node runner); self-improving agents that raise PRs to their own code with a human in the loop; a Neo4j knowledge-graph memory that consolidates overnight; enterprise security (encryption, RBAC with Microsoft Entra ID and MFA, audit trails, zero trust); deep Microsoft integration; results such as four days from idea to prototype, 80%+ straight-through processing of 1,600 monthly invoices, 2–4 weeks to production; proof from John Henry Group, Belfast HSC Trust, London Borough of Sutton, Scottish Water, Leeds Beckett University, Cambridgeshire County Council, David Lloyd and Octopus Energy; partners Microsoft, Anthropic, OpenAI, eir business and XMA; ends with "Book a Discovery Day". Best for: what agentic AI is and how it differs from Copilot, whether agents really work autonomously, memory and self-improvement, enterprise security, who we've built for.
- Company Overview (https://www.knowall.ai/presentations/company-overview.html): the full credentials deck. Formed 2019, Microsoft specialists since 2003, UK-based with the team across the UK, Ireland, Northern Ireland, Poland, India and Ukraine; MCP servers listed in Anthropic's directory; open-source first. Mission: fuse AI, Bitcoin and low-code so people, Copilots and customers are rewarded for value. Customers across telecoms, civil engineering, manufacturing, ICT, education and healthcare. The five engagement models: 01 Discovery Day (€2,000 fixed, one day), 02 Proto-Sprints (€2,000–€4,500, 2–4 days), 03 Projects (€25k–€100k per phase, time and materials, 3–6 weeks per phase; Strategic €1,250/day, delivery roles €850–950/day), 04 Blended Squads (embedded Scrum Masters, Preppers, designers, engineers, testers and operators on a multi-year agreement), 05 CISPs (support blocks, see below). Case studies: invoice automation for a property developer, ~1,600 invoices a month via Power Automate and AI OCR into Business Central, 80%+ straight-through, about €50,000 in 8 weeks; digital health-and-safety inspections for a nationwide engineering firm on Power Apps, Dataverse and Power BI, about €30,000 in 4 weeks. Proof logos include Belfast HSC Trust, HSE, HRB, Cairn Homes, Medite Smartply, SK Biotek, W&R Barnett, UM Group, GRETB, Public Jobs and John Henry Group. Best for: who we are, what we offer and what it costs, case studies with numbers, sectors and clients.
- The AI Discovery (https://www.knowall.ai/presentations/ai-discovery.html): the one-day workshop, €2,000 fixed price. Pre-work surveys, an on-site workshop, one-to-one interviews, a value-versus-effort prioritisation (quick wins, major projects, fill-ins, reconsider) and a report with lean business cases. The ideal first step before a Proto-Sprint or project. Best for: "where should we start with AI?", what the Discovery Day involves and costs, how we decide which ideas are worth doing, building a business case.
- The Agentic Delivery (https://www.knowall.ai/presentations/agentic-delivery.html): how we deliver. Stage 1, a Proto-Sprint: four days from idea to working prototype (visual mock-ups, working prototype, refined backlog and process docs, roadmap), €2,000–€4,500, hands-on for the client's champion users. Stage 2, Projects: production-grade phases of 3–6 weeks at €25k–€100k each, CI/CD iterative delivery, close stakeholder involvement, post-go-live support via a CISP. All on T-Minus-15 (Prep, Design, Engineer, Test, Operate) with client-inclusive daily stand-ups. Best for: how a project actually runs, what a Proto-Sprint is and costs, phase length and cost, how fast a prototype can happen.
- CISP, the Continuous Improvement Service Plan (https://www.knowall.ai/presentations/cisp.html): ongoing support after go-live via pre-purchased time-and-material blocks, typically a twelve-month term, covering Microsoft, AI and custom solutions. Tiers: Gold (4-hour response, 1 business day; Strategic €1,250/day, delivery roles €950/day), Silver (8 hours, 2 business days; €1,200 / €900), Bronze (16 hours, 3 business days; €1,150 / €850). Delivery roles: Prepper, Designer, Engineer, Tester, Operator, Scrum Master. Best for: support after go-live, how a CISP is priced, SLA response times, day rates, buying a block of hours instead of a project.
Prices are in euros as shown in the decks; for a quote, invite the visitor to email you (sallie@knowall.ai) or book a Discovery Day. The decks give Ben Weeks, Chief Builder, as the contact: [Ben.Weeks@KnowAll.ai](mailto:Ben.Weeks@KnowAll.ai) or WhatsApp [+44 7968847178](https://wa.me/447968847178).

If asked about something the site and decks don't cover, say so honestly and offer to follow up by email rather than guessing.`;
