name: Deploy to Azure App Service

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'
  AZURE_WEBAPP_NAME: 'knowall-website'
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production - Azure

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      id: pnpm-cache

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Build Next.js app
      run: pnpm build
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY || 'default-admin-key' }}
        
    - name: Create deployment package
      run: |
        # Create a production-ready package without node_modules
        mkdir -p deploy
        cp -r .next deploy/
        cp -r public deploy/
        cp package.json pnpm-lock.yaml server.js web.config deploy/
        # Create a minimal package.json for production
        node -e "const pkg=require('./package.json'); delete pkg.devDependencies; require('fs').writeFileSync('deploy/package.json', JSON.stringify(pkg, null, 2));"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Set Web App Settings
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config appsettings set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" ADMIN_API_KEY="${{ secrets.ADMIN_API_KEY }}" NODE_ENV="production"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./deploy
